version: '3.7'

services:
  # Docker
  portainer:
    image: portainer/portainer:${PORTAINER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    command: -H unix:///var/run/docker.sock --admin-password "${PORTAINER_PASSWORD}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - traefik
      - ddstack
    labels:
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.frontend.rule=Host:portainer.traefik.docker"
      - "traefik.port=9000"

  jenkins:
    container_name: ${COMPOSE_PROJECT_NAME}_jenkins
    build:
      context: ./devops/jenkins
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    ports:
      - 5000:5000
    networks:
      - traefik
      - ddstack
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:jenkins.traefik.docker"
      - "traefik.port=8080"

  ansistrano:
    container_name: ${COMPOSE_PROJECT_NAME}_ansistrano
    build:
      context: devops/ansistrano
    volumes:
      - ./devops/ansistrano/conf/hosts:/etc/ansible/hosts
      - ./devops/ansistrano/playbooks:/etc/ansible/playbooks
    environment:
      - ANSISTRANO_WEBSERVERS=${ANSISTRANO_WEBSERVERS}
    healthcheck:
      test: ansible all -m ping
      interval: 2s
      timeout:  2s
      retries:  3
    networks:
      - ddstack

volumes:
  portainer_data:
    driver: local
  jenkins_data:
    driver: local
