version: '3.7'

services:
  # Docker
  portainer:
    image: portainer/portainer:${PORTAINER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.portainer"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.portainer.docker"
      - "traefik.port=9000"
      - "traefik.frontend.passHostHeader=true"

  jenkins:
    container_name: ${COMPOSE_PROJECT_NAME}_jenkins
    build:
      context: ./devops/jenkins
      args:
        - JENKINS_VERSION=${JENKINS_VERSION}
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_USER=${JENKINS_USER}
      - JENKINS_PASSWORD=${JENKINS_PASSWORD}
    ports:
      - 5000:5000
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.jenkins"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.jenkins.docker"
      - "traefik.port=8080"
      - "traefik.frontend.passHostHeader=true"

volumes:
  portainer_data:
    driver: local
  jenkins_data:
    driver: local

networks:
  default:
    external:
      name: traefik
