version: '3.7'

services:
  # RabbitMQ (Message queuing service)
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
      - RABBITMQ_VHOST=/
    networks:
      - traefik
      - ddstack
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rabbitmq"
      - "traefik.frontend.rule=Host:rabbitmq.traefik.docker"
      - "traefik.port=15672"

  # Streamsets (ETL)
  streamsets:
    image: streamsets/datacollector:${STREAMSETS_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_streamsets
    volumes:
      - sdc_data:/data:rw
    networks:
      - traefik
      - ddstack
    labels:
      - "traefik.enable=true"
      - "traefik.backend=streamsets"
      - "traefik.frontend.rule=Host:streamsets.traefik.docker"
      - "traefik.port=18630"

volumes:
  rabbitmq_data:
    driver: local
  sdc_data:
    driver: local
