version: '3.7'

services:
  # Web
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    build:
      context: traefik
      args:
        - TRAEFIK_VERSION=${TRAEFIK_VERSION}
    command: --api
      --api.entrypoint=traefik
      --api.dashboard=true
      --docker
      --docker.domain=dev
      --logLevel=${TRAEFIK_LOG_LEVEL}
      --defaultEntryPoints='http,https'
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS:/ssl/certs/traefik.cert.pem,/ssl/private/traefik.key.pem'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/ssl/certs:/ssl/certs
      - ./traefik/ssl/private:/ssl/private
    ports:
      - 80:80
      - 443:443
      - 14500:14500
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.traefik"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.traefik.docker"
      - "traefik.port=8080"
      - "traefik.frontend.passHostHeader=true"

networks:
  default:
    external:
      name: traefik
