version: '3.7'

services:
  # Web
  traefik:
    container_name: ${COMPOSE_PROJECT_NAME}_traefik
    build:
      context: proxy/traefik
      args:
        - TRAEFIK_VERSION=${TRAEFIK_VERSION}
    command: --debug=${TRAEFIK_DEBUG} --logLevel=${TRAEFIK_LOG_LEVEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./proxy/traefik/conf/traefik.toml:/etc/traefik/traefik.toml
      - ./proxy/traefik/ssl:/etc/ssl
#      - ./proxy/traefik/acme.json:/etc/traefik/acme.json
    ports:
      - 80:80
      - 443:443
      - 14500:14500
    networks:
      - traefik
      - ddstack
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.traefik.docker"
      - "traefik.port=8080"
      - "traefik.frontend.passHostHeader=true"

networks:
  ddstack:
    name: ddstack
  traefik:
    name: traefik
