version: '3.7'

services:
  # Network sniffing
  wireshark:
    image: ffeldhaus/wireshark:${WIRESHARK_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_wireshark
    privileged: true
    network_mode: "service:traefik"
    depends_on:
      - traefik
    environment:
      - XPRA_PW=${WIRESHARK_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=wireshark"
      - "traefik.frontend.rule=Host:wireshark.traefik.docker"
      - "traefik.port=14500"
      - "traefik.frontend.headers.SSLRedirect=true"

  # Mails
  mailcatcher:
    image: schickling/mailcatcher:${MAILCATCHER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    networks:
      - traefik
      - ddstack
    labels:
      - "traefik.enable=true"
      - "traefik.backend=mailcatcher"
      - "traefik.frontend.rule=Host:mailcatcher.traefik.docker"
      - "traefik.port=1080"

volumes:
  sdc_data:
    driver: local
