version: '3.7'

services:
  # SQL
  mysql:
    image: percona:${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "show databases"
      interval: 5s
      timeout:  1s
      retries:  3
    ports:
      - 3306:3306
    networks:
      - ddstack

  # Redis
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    build:
      context: storage/redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./storage/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - ddstack

  # FTP
  sftp-server:
    image: atmoz/sftp:${SFTP_SERVER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_sftp-server
    volumes:
      - ./storage/ftp/etc/sftp.d/fix-permissions.sh:/etc/sftp.d/fix-permissions
      - ./storage/ftp/upload:/home/ftp/upload
    command: ${FTP_USER}:${FTP_PASSWORD}:1001
    ports:
      - "${FTP_PORT}:22"
    networks:
      - ddstack

volumes:
  mysql_data:
    driver: local
