version: '3.7'

services:
  # SQL
  mysql:
    image: percona:${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "show databases"
      interval: 5s
      timeout:  1s
      retries:  3
    ports:
      - 3306:3306
    labels:
      - "traefik.enable=false"

  adminer:
    image: adminer:${ADMINER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_adminer
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.adminer"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.adminer.docker"
      - "traefik.port=8080"
      - "traefik.frontend.passHostHeader=true"

  sqlpad:
    image: sqlpad/sqlpad:${SQLPAD_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_sqlpad
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.sqlpad"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.sqlpad.docker"
      - "traefik.port=3000"
      - "traefik.frontend.passHostHeader=true"

  # Redis
  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    build:
      context: storage/redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./storage/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    labels:
      - "traefik.enable=false"

  redis-commander:
    image: rediscommander/redis-commander:${REDIS_COMMANDER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_redis-commander
    environment:
      - REDIS_HOSTS=${REDIS_URI}
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.redis-commander"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.redis-commander.docker"
      - "traefik.port=8081"
      - "traefik.frontend.passHostHeader=true"

  redis-memtier_benchmark:
    container_name: ${COMPOSE_PROJECT_NAME}_redis-memtier_benchmark
    build:
      context: storage/redis-memtier_benchmark
      args:
        - REDIS_MEMTIER_VERSION=${REDIS_MEMTIER_VERSION}
        - REDIS_SERVER=${REDIS_SERVER}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    labels:
      - "traefik.enable=false"

  # ES
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_elasticsearch
    depends_on:
      - mysql
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "xpack.security.enabled=false"
    ports:
      - 9200:9200
    labels:
      - "traefik.enable=false"

  sense:
    image: s12v/sense:${SENSE_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_sense
    labels:
      - "traefik.backend=${COMPOSE_PROJECT_NAME}.sense"
      - "traefik.port=5601"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.sense.docker"
      - "traefik.frontend.passHostHeader=true"

  # FTP
  sftp-server:
    image: atmoz/sftp:${SFTP_SERVER_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_sftp-server
    volumes:
      - ./storage/ftp/etc/sftp.d/fix-permissions.sh:/etc/sftp.d/fix-permissions
      - ./storage/ftp/upload:/home/ftp/upload
    command: ${FTP_USER}:${FTP_PASSWORD}:1001
    ports:
      - "${FTP_PORT}:22"
    labels:
      - "traefik.enable=false"

volumes:
  elasticsearch_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: traefik
